"""empty message

Revision ID: 405e3d7d1bc5
Revises: b40854c41168
Create Date: 2021-09-21 10:28:42.376320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '405e3d7d1bc5'
down_revision = 'b40854c41168'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('first_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'first_name')
    # ### end Alembic commands ###
