"""empty message

Revision ID: 9555fc0131b3
Revises: 555ae80cb46e
Create Date: 2021-08-18 10:56:18.656686

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "9555fc0131b3"
down_revision = "555ae80cb46e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "distributor", ["name"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "distributor", type_="unique")
    # ### end Alembic commands ###
