"""empty message

Revision ID: b40854c41168
Revises: 8527b528c4c0
Create Date: 2021-09-21 10:28:23.923259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b40854c41168'
down_revision = '8527b528c4c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'first_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
